### ISSUE TITLE
Disable click event throttling

### ISSUE THREAD

**Issue by telwing** [I2Djs/I2Djs#66]
**Is your feature request related to a problem? Please describe.**
I am trying to build something that requires a lot of fast clicks, but the clicks are being throttled.

**Describe the solution you'd like**
A way to disable this throttling.

**Describe alternatives you've considered**
I'm not sure if this is a result of the double-click timer, but maybe the `dblclick` listener could be optional.

**Additional context**
Here's a reproduction of what I am describing. If you look in the console and start clicking very fast, you will see the `i2djs` counter falls behind the `native` counter.
https://codesandbox.io/s/unruffled-villani-gpm8j

**Comment by nswamy14** [comment]
Hi @telwing ,
Thank you for raising an issue.
Yes, you are right, the issue is because of the double-click timer.  
However, in the latest code of Github, the issue has been taken care of along with many other improvements and features, which I am yet to release soon. Till then you can refer to the latest code of the Github master branch.
Do let me know if you need any more understanding.

Thank you,
@nswamy14

**Comment by telwing** [comment]
I see, I appreciate the response. Thank you!

**Comment by nswamy14** [comment]
Fixed as a part of **v3.5.0** release.
